### Step 1: Creating Token

In [8]:
with open(r"D:\Data_Science_Study\Course_Pracitse_Code\GenerativeAi\LLM_From_Scratch\Building-LLMs-from-Scratch\0. Data\the-verdict.txt" , "r" , encoding = "utf-8") as f:
    raw_text = f.read()


print("Total Number of Character:", len(raw_text))
print(raw_text[:99])

Total Number of Character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


### Our Aim is to tokenize this 20-479 chracter short story into individual words and special character that we can trun into embedding for LLM training

### Split text to Token

In [2]:
import re
preprocessed = re.split(r'([,._!?:;"()\']|--|\s)', raw_text)
preprocessed = [item for item in preprocessed if item.strip()]

print(len(preprocessed))
print(preprocessed[:35])

4690
['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory']


### Step :2 Creating Token ID

### Creating simple Tokennizer Class

In [3]:
all_tokens = sorted(list(set(preprocessed)))

all_tokens .extend(["<|endoftext|>","<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

print(len(vocab.items()))

1132


In [4]:
for i,item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [5]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s ,i in vocab.items()}
    

    def encode(self,text):
        preprocessed = re.split(r'([,._!?:;"()\']|--|\s)', text)
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]

        return ids
    

    def decode(self,ids):
        text = " ".join([self.int_to_str[i] for i in ids])

        # replace spaces for pamctuations
        text  = re.sub(r'\s+([,.?!"()\'])', r'\1',text)

        return text

In [6]:
tokenizer = SimpleTokenizerV2(vocab)
tokenizer.encode(raw_text)

[53,
 44,
 149,
 1003,
 57,
 38,
 818,
 115,
 256,
 486,
 6,
 1002,
 115,
 500,
 435,
 392,
 6,
 908,
 585,
 1077,
 709,
 508,
 961,
 1016,
 663,
 1016,
 535,
 987,
 5,
 568,
 988,
 538,
 722,
 549,
 496,
 5,
 533,
 514,
 370,
 549,
 748,
 5,
 661,
 115,
 841,
 1102,
 5,
 157,
 397,
 547,
 568,
 115,
 1066,
 727,
 988,
 84,
 7,
 3,
 99,
 53,
 818,
 1003,
 585,
 1120,
 530,
 208,
 85,
 734,
 34,
 7,
 4,
 1,
 93,
 538,
 722,
 549,
 496,
 1,
 6,
 987,
 1077,
 1089,
 988,
 1112,
 242,
 585,
 7,
 53,
 244,
 535,
 67,
 7,
 37,
 100,
 6,
 549,
 602,
 25,
 897,
 6,
 326,
 549,
 1042,
 116,
 7,
 1,
 73,
 297,
 585,
 2,
 850,
 498,
 1016,
 866,
 988,
 1059,
 722,
 697,
 769,
 2,
 1083,
 1051,
 9,
 239,
 53,
 359,
 2,
 970,
 998,
 722,
 987,
 5,
 66,
 7,
 83,
 6,
 988,
 646,
 1016,
 16,
 584,
 145,
 53,
 998,
 722,
 7,
 1,
 93,
 1116,
 5,
 727,
 67,
 7,
 100,
 2,
 850,
 633,
 5,
 693,
 586,
 114,
 847,
 114,
 177,
 1002,
 994,
 1088,
 827,
 568,
 156,
 389,
 1069,
 722,
 677,
 7,
 14,
 585,
 1077

### Some more token can be added :
### <BOS> : Begining of text
### <EOS> : End of text
### [PAD] : Padding ( batch may have varriying length so to see batch have same length of text size we can agument [PAD] etc)

### Byte Pair Encoding

In [9]:
import tiktoken

In [10]:
tokenizer  = tiktoken.get_encoding('gpt2')

In [11]:
integers = tokenizer.encode(raw_text , allowed_special={"<|endoftext|>"})
print(integers)

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11, 290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536, 5469, 438, 14363, 938, 4842, 1650, 353, 438, 2934, 489, 3255, 465, 48422, 540, 450, 67, 3299, 13, 366, 5189, 1781, 340, 338, 1016, 284, 3758, 262, 1988, 286, 616, 4286, 705, 1014, 510, 26, 475, 314, 836, 470, 892, 286, 326, 11, 1770, 13, 8759, 2763, 438, 1169, 2994, 284, 943, 17034, 318, 477, 314, 892, 286, 526, 383, 1573, 11, 319, 9074, 13, 536, 5469, 338, 11914, 11, 33096, 663, 4808, 3808, 62, 355, 996, 484, 547, 12548, 287, 281, 13079, 410, 12523, 286, 

## Create INPUT Target Pairs

In [12]:
context_size = 4 # length of input

x = integers[:context_size]
y = integers[1:context_size+1]


print(f"x: {x}")
print(f"y:     {y}")

x: [40, 367, 2885, 1464]
y:     [367, 2885, 1464, 1807]


In [13]:
for i in range(1, context_size+1):
    context = integers[:i]
    desired = integers[i]

    print(context , "----->" , desired)

[40] -----> 367
[40, 367] -----> 2885
[40, 367, 2885] -----> 1464
[40, 367, 2885, 1464] -----> 1807


In [14]:
for i in range(1, context_size+1):
    context = integers[:i]
    desired = integers[i]

    print(tokenizer.decode(context) , "----->" , tokenizer.decode([desired]))

I ----->  H
I H -----> AD
I HAD ----->  always
I HAD always ----->  thought


### Implementing Data Loader

In [15]:
from torch.utils.data import Dataset, DataLoader
import torch

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids  = []
        self.target_ids = []

        # tokenize the entire text
        token_ids = tokenizer.encode(txt,allowed_special={"<|endoftext|>"})

        # use sliding window
        for i in range(0,len(token_ids)- max_length, stride):
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+1: i+max_length +1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

        
    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [16]:
def create_dataloader_v1(txt, batch_size = 4, max_length = 256,
                         stride = 128, shuffle = True,
                         drop_last = True, num_workers = 0):
    

    tokenizer = tiktoken.get_encoding('gpt2')

    dataset = GPTDatasetV1(txt, tokenizer, max_length , stride)

    dataloader = DataLoader(
        dataset,
        batch_size= batch_size,
        shuffle =shuffle,
        drop_last=drop_last,
        num_workers= num_workers
    )

    return dataloader 

In [17]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4, stride=4, shuffle=False
)

In [18]:
data_iter = iter(dataloader)

first_batch = next(data_iter)

In [19]:
print(f"First Batch is : {first_batch}")
print(f"Second Batch is : {next(data_iter)}")

First Batch is : [tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]]), tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])]
Second Batch is : [tensor([[  287,   262,  6001,   286],
        [  465, 13476,    11,   339],
        [  550,  5710,   465, 12036],
        [   11,  6405,   257,  5527],
        [27075,    11,   290,  4920],
        [ 2241,   287,   257,  4489],
        [   64,   319,   262, 34686],
        [41976,    13,   357, 10915]]), tensor([[  262,  6001,   286,   465],
       

## Token Embedding

In [20]:
input_ids = torch.tensor([2,3,5,1])

In [21]:
vocab_size = 6
output_dim =3


torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [22]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [23]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [25]:
print(embedding_layer(torch.tensor([2,3,5,1])))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


### Positional Embedding

In [26]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size , output_dim)

In [30]:
token_embedding_layer.weight.shape

torch.Size([50257, 256])

In [31]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4, stride=4, shuffle=False
)

data_iter = iter(dataloader)

inputs, targets = next(data_iter)

In [32]:
print("Token IDs:\n", inputs)
print("Input Shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Input Shape:
 torch.Size([8, 4])


In [34]:
token_embeddings = token_embedding_layer(inputs)

print("Token Embedding Shape\n", token_embeddings.shape)

Token Embedding Shape
 torch.Size([8, 4, 256])


In [40]:
token_embeddings

tensor([[[ 0.4913,  1.1239,  1.4588,  ..., -0.3995, -1.8735, -0.1445],
         [ 0.4481,  0.2536, -0.2655,  ...,  0.4997, -1.1991, -1.1844],
         [-0.2507, -0.0546,  0.6687,  ...,  0.9618,  2.3737, -0.0528],
         [ 0.9457,  0.8657,  1.6191,  ..., -0.4544, -0.7460,  0.3483]],

        [[ 1.5460,  1.7368, -0.7848,  ..., -0.1004,  0.8584, -0.3421],
         [-1.8622, -0.1914, -0.3812,  ...,  1.1220, -0.3496,  0.6091],
         [ 1.9847, -0.6483, -0.1415,  ..., -0.3841, -0.9355,  1.4478],
         [ 0.9647,  1.2974, -1.6207,  ...,  1.1463,  1.5797,  0.3969]],

        [[-0.7713,  0.6572,  0.1663,  ..., -0.8044,  0.0542,  0.7426],
         [ 0.8046,  0.5047,  1.2922,  ...,  1.4648,  0.4097,  0.3205],
         [ 0.0795, -1.7636,  0.5750,  ...,  2.1823,  1.8231, -0.3635],
         [ 0.4267, -0.0647,  0.5686,  ..., -0.5209,  1.3065,  0.8473]],

        ...,

        [[-1.6156,  0.9610, -2.6437,  ..., -0.9645,  1.0888,  1.6383],
         [-0.3985, -0.9235, -1.3163,  ..., -1.1582, -1.13

In [36]:
context_length = 4
pos_embedding_layer =  torch.nn.Embedding(context_length, output_dim)
pos_embedding_layer.weight

Parameter containing:
tensor([[-2.0049,  0.5874, -0.4354,  ...,  0.7926, -0.0893, -0.5755],
        [ 0.2844,  0.6477, -0.0762,  ...,  0.7396,  0.0491,  1.3986],
        [ 0.9397,  0.9033, -0.2303,  ...,  0.4648, -0.8137, -0.3211],
        [ 0.8994,  0.4214, -0.0861,  ...,  0.0078, -1.9325,  0.2861]],
       requires_grad=True)

In [ ]:
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [38]:
final_embeddin_layer = token_embeddings + pos_embeddings
final_embeddin_layer.shape

torch.Size([8, 4, 256])

In [39]:
final_embeddin_layer

tensor([[[-1.5136,  1.7113,  1.0235,  ...,  0.3931, -1.9628, -0.7200],
         [ 0.7324,  0.9013, -0.3417,  ...,  1.2393, -1.1500,  0.2142],
         [ 0.6890,  0.8486,  0.4385,  ...,  1.4266,  1.5599, -0.3739],
         [ 1.8451,  1.2871,  1.5330,  ..., -0.4467, -2.6785,  0.6344]],

        [[-0.4588,  2.3243, -1.2201,  ...,  0.6922,  0.7691, -0.9176],
         [-1.5778,  0.4563, -0.4574,  ...,  1.8616, -0.3004,  2.0076],
         [ 2.9244,  0.2550, -0.3717,  ...,  0.0807, -1.7493,  1.1267],
         [ 1.8641,  1.7188, -1.7068,  ...,  1.1540, -0.3528,  0.6830]],

        [[-2.7762,  1.2446, -0.2691,  ..., -0.0117, -0.0351,  0.1671],
         [ 1.0889,  1.1524,  1.2160,  ...,  2.2044,  0.4588,  1.7191],
         [ 1.0192, -0.8603,  0.3447,  ...,  2.6471,  1.0093, -0.6846],
         [ 1.3260,  0.3567,  0.4825,  ..., -0.5131, -0.6260,  1.1334]],

        ...,

        [[-3.6204,  1.5485, -3.0791,  ..., -0.1718,  0.9995,  1.0629],
         [-0.1141, -0.2758, -1.3925,  ..., -0.4185, -1.08